### PR TITLE
Add support for TOML

### LINKED ISSUE #12: Add support for TOML
TOML ([Tom's Obvious Minimal Language](https://toml.io/en/)) is a "config file format for humans". It is readable, unambiguous, and has a standardised format. It is also "designed to map unambiguously to a hash table". As such, it is a good choice for creating configuration or data files. Python 3.11 will release a TOML parser in the standard library.

### PR DESCRIPTION
**Pull request by wessven**
Resolves issue #12

### CODE REVIEW

**Comment by LucasVanHaaren** [comment]
Hello @wessven,

Thanks a lot for your work, this is a very nice feature for the project ! 
I will try it on my side and do the merge and deploy tasks as soon as possible

(I really need to build a good CI-CD pipeline to ensure some automated testing / deploying  :sweat_smile:)

**Review by LucasVanHaaren — COMMENTED** [review]
Refactoring `is_valid file` function to `get_file_type` is fine, I will look into this in detail in the next few days.

**Comment by LucasVanHaaren** [comment]
Hi @wessven,

I am testing your work in order to merge it soon. Can you please say me what is the version of pelican you used to run ?
I am facing issue with latest version so I released a downgrade of pelican supported version yesterday.

See Issue #11

**Comment by wessven** [comment]
Hi @LucasVanHaaren , I used Pelican 4.7.2.  I see a new version (4.8.0) was released two weeks ago.  I'm not able to test against it immediately, but if you need me to I can try and do that later.

**Comment by LucasVanHaaren** [comment]
As I just released v1.2.0 which adds TOML support, I close this PR !

I still want to thank you for your great work, and I’m sorry it took me so long to review your PR :heart:

**Pull request closed without merging**
